name: Publish to Rubygems

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install dependencies
      run: bundle install
    - name: gem build
      run: gem build tlapse.gemspec
    - name: gem push
      run: gem push "tlapse-$(git describe --tags).gem"
